### ISSUE TITLE
Translation of Nemo's Campfires into Ukrainian

### ISSUE THREAD

**Issue by StarmanMine142** [NemoNotFound/NemosCampfires#2]
Could you add the Ukrainian translation created by me?

[uk_ua.json](https://github.com/user-attachments/files/18014133/uk_ua.json)

**Comment by NemoNotFound** [comment]
Hey,
please create a PR for that.
I don't click on links

**Comment by StarmanMine142** [comment]
okay

**Comment by StarmanMine142** [comment]
@NemoNotFound

I thought it would be easier to upload the Ukrainian translation file to your Discord server

Chat —> general

**Comment by NemoNotFound** [comment]
Okay, I'll close this ticket then!
